# -*- coding: utf-8 -*-
"""Final_Colab_Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y7z9bu0Nn5vuxT4MsiBBQH6DVpVL1Uoe
"""

# @title Cell 1: Setup & Database Connection
import requests, time, json
import io
import base64
from datetime import datetime
from collections import defaultdict
import nltk
from nltk.stem import WordNetLemmatizer
import re
import pandas as pd
import matplotlib.pyplot as plt
import google.generativeai as genai
from google.colab import output

# Download NLTK data
nltk.download('wordnet')
nltk.download('omw-1.4')

# --- SETTINGS & CONNECTIONS ---
class FirebaseClient:
    def __init__(self, url):
        self.url = url if url.endswith('/') else url + '/'

    def post(self, endpoint, data):
        endpoint = endpoint if not endpoint.startswith('/') else endpoint[1:]
        try:
            response = requests.post(f"{self.url}{endpoint}.json", json=data)
            return response.json()
        except Exception as e:
            print(f"❌ Firebase Post Error: {e}")
            return None

    def get(self, endpoint, param):
        endpoint = endpoint if not endpoint.startswith('/') else endpoint[1:]
        try:
            response = requests.get(f"{self.url}{endpoint}.json")
            return response.json()
        except Exception as e:
            print(f"❌ Firebase Get Error: {e}")
            return None

    def put(self, endpoint, child, data):
        endpoint = endpoint if not endpoint.startswith('/') else endpoint[1:]
        try:
            url = f"{self.url}{endpoint}{child}.json" if child else f"{self.url}{endpoint}.json"
            response = requests.put(url, json=data)
            return response.json()
        except Exception as e:
            print(f"❌ Firebase Put Error: {e}")
            return None

# Connection to Firebase
URL_SAVE = "https://cloudrageng-default-rtdb.firebaseio.com/"
FBconn = FirebaseClient(URL_SAVE)

print(f"✅ Connected to Save DB: {URL_SAVE}")

# @title Cell 2: Ingestion Microservice (Sensors)
BASE_URL = "https://server-cloud-v645.onrender.com/"

def fetch_and_save_data_from_braude(feed_name: str, limit: int) -> str:
    """ Fetch from Braude Server -> Save to Firebase """
    limit = int(limit)
    print(f"🚀 Microservice 'Ingestion' started: Fetching {limit} items for feed '{feed_name}'...")

    try:
        response = requests.get(
            f"{BASE_URL}/history",
            params={"feed": feed_name, "limit": limit},
            timeout=60
        )
        response.raise_for_status()
        data = response.json()

        if "data" in data and len(data["data"]) > 0:
            messages = []
            samples = data["data"][::-1]

            for i, sample in enumerate(samples):
                raw_value = sample["value"]
                server_time = sample["created_at"]
                temp_val = hum_val = soil_val = 0.0

                # JSON Parsing Logic
                if feed_name == "json":
                    payload = {}
                    if isinstance(raw_value, str):
                        try:
                            payload = json.loads(raw_value)
                        except:
                            payload = {}
                    elif isinstance(raw_value, dict):
                        payload = raw_value

                    temp_val = float(payload.get("temperature", 0))
                    hum_val = float(payload.get("humidity", 0))
                    soil_val = float(payload.get("soil", 0))
                else:
                    try: val_float = float(raw_value)
                    except: val_float = 0.0
                    if feed_name == "temperature": temp_val = val_float
                    elif feed_name == "humidity": hum_val = val_float
                    elif feed_name == "soil": soil_val = val_float

                reading = {
                    "timestamp": datetime.now().isoformat(),
                    "original_server_time": server_time,
                    "temperature": temp_val,
                    "humidity": hum_val,
                    "soil": soil_val,
                    "source": f"braude_server_{feed_name}"
                }

                if FBconn:
                    FBconn.post("/sensor_data", reading)
                    messages.append(f"💾 [{i+1}] Saved to DB: {feed_name}={raw_value}")
                else:
                    messages.append(f"⚠️ [{i+1}] Not saved (DB Error)")

            return "<br>".join(messages) + "<br>✨ Process Complete!"
        else:
            return f"⚠️ Server returned empty or invalid data."
    except Exception as e:
        return f"❌ Error: {str(e)}"

output.register_callback('fetch_and_save_data_from_braude', fetch_and_save_data_from_braude)
print("✅ Ingestion Service Registered.")

# @title Cell 3: Upload Sources Metadata
# Define source URLs
SOURCE_URLS = {
    "Deep learning for plant disease (ScienceDirect)":
        "https://www.sciencedirect.com/science/article/abs/pii/S1537511018307797",
    "Image processing for disease detection (ScienceDirect)":
        "https://www.sciencedirect.com/science/article/abs/pii/S0168169910000438",
    "Review of optical sensors (Springer)":
        "https://link.springer.com/article/10.1007/s13593-014-0246-1",
    "Hyperspectral remote sensing (ScienceDirect)":
        "https://www.sciencedirect.com/science/article/abs/pii/S0034425712003793",
    "Review on ML for plant disease (Materials Today)":
        "https://www.sciencedirect.com/science/article/abs/pii/S2214785323009343"
}

print("🚀 Uploading Source Metadata to Firebase...")

# Optional: Clear old sources
try:
    requests.delete(f"{FBconn.url}Sources.json")
except:
    pass

count = 1
for title, url in SOURCE_URLS.items():
    data_to_upload = {
        "URL": url,
        "source_Id": count,
        "title": title
    }
    FBconn.put('Sources', str(count), data_to_upload)
    print(f"✅ Source #{count} saved: {title}")
    count += 1

# @title Cell 4: Backend Services (Rich Content Implementation) 🧠
import requests
import re
from collections import defaultdict
import pandas as pd
import matplotlib.pyplot as plt
import io
import base64
import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import google.generativeai as genai
from google.colab import output

# --- Setup ---
nltk.download('stopwords', quiet=True)
nltk.download('punkt', quiet=True)

GEMINI_API_KEY = "AIzaSyA9sBMXVeoZit34XMmA_xTyHL3BefMJdQw" # Your Key
genai.configure(api_key=GEMINI_API_KEY)
model = genai.GenerativeModel("gemini-2.5-flash")

# --- Rich Paper Content ---
SAMPLE_PAPERS = [
    {
        'title': 'Plant disease identification from individual lesions and spots using deep learning',
        'content': """This study proposes a method for increasing the size and diversity of plant disease image datasets...""",
        'url': 'https://doi.org/10.1016/j.biosystemseng.2019.02.002'
    },
    {
        'title': 'A review of advanced techniques for detecting plant diseases',
        'content': """This paper reviews advanced techniques for ground-based plant disease detection...""",
        'url': 'https://doi.org/10.1016/j.compag.2010.02.007'
    },
    {
        'title': 'Advanced methods of plant disease detection. A review',
        'content': """Plant diseases cause major economic losses. This review describes modern detection methods...""",
        'url': 'https://doi.org/10.1007/s13593-014-0246-1'
    },
    {
        'title': 'Development of spectral indices for detecting and identifying plant diseases',
        'content': """The aim of this study was to develop specific spectral disease indices (SDIs)...""",
        'url': 'https://doi.org/10.1016/j.rse.2012.09.019'
    },
    {
        'title': 'Agricultural plant diseases identification: From traditional approach to deep learning',
        'content': """This paper reviews the transition from traditional image processing to Deep Learning...""",
        'url': 'https://doi.org/10.1016/j.matpr.2023.02.370'
    }
]

# Global Storage
GLOBAL_INDEX = defaultdict(list)
GLOBAL_DOCS = {}
DOC_METADATA = {}
FRONTEND_SEARCH_DATA = []

# --- Part 1: Inverted Index ---

def clean_text(text):
    text = re.sub(r'[^a-zA-Z\s]', '', str(text))
    return text.lower()

def remove_stop_words(word_list):
    stop_words = set(stopwords.words('english'))
    stop_words.update(['use', 'used', 'using', 'study', 'paper', 'result', 'method', 'analysis', 'based'])
    return [w for w in word_list if w not in stop_words]

def apply_stemming(word_list):
    stemmer = PorterStemmer()
    return [stemmer.stem(w) for w in word_list]

def build_inverted_index():
    global GLOBAL_INDEX, GLOBAL_DOCS, DOC_METADATA, FRONTEND_SEARCH_DATA

    print("🔄 Building Inverted Index...")
    GLOBAL_INDEX = defaultdict(list)
    GLOBAL_DOCS = {}
    FRONTEND_SEARCH_DATA = []

    for i, paper in enumerate(SAMPLE_PAPERS):
        doc_id = str(i)
        content = paper['content']
        title = paper['title']

        # Store for RAG
        GLOBAL_DOCS[doc_id] = content
        DOC_METADATA[doc_id] = {'title': title, 'url': paper['url']}

        # Prepare for Frontend Search - התיקון כאן: הוספנו את ה-URL
        FRONTEND_SEARCH_DATA.append({
            "title": title,
            "content": content[:200] + "...",
            "tags": clean_text(title).split(),
            "url": paper['url']
        })

        # Process for Indexing
        clean_content = clean_text(content)
        words = clean_content.split()
        words = remove_stop_words(words)
        stemmed_words = apply_stemming(words)

        for word in stemmed_words:
            if doc_id not in GLOBAL_INDEX[word]:
                GLOBAL_INDEX[word].append(doc_id)

    try:
        if 'FBconn' in globals():
            FBconn.put('/', 'InvertedIndex', dict(GLOBAL_INDEX))
            print(f"💾 Index saved to Firebase: {len(GLOBAL_INDEX)} terms.")
    except Exception as e:
        print(f"⚠️ Firebase save failed (Working locally): {e}")

build_inverted_index()

# --- Part 2: RAG Engine ---

def retrieve_documents_rag(query):
    documents = list(GLOBAL_DOCS.values())
    doc_ids = list(GLOBAL_DOCS.keys())

    if not documents: return None, None

    vectorizer = TfidfVectorizer(stop_words='english')
    tfidf_matrix = vectorizer.fit_transform(documents)
    query_vec = vectorizer.transform([query])

    cosine_similarities = cosine_similarity(query_vec, tfidf_matrix).flatten()
    most_related_idx = cosine_similarities.argmax()

    if cosine_similarities[most_related_idx] > 0.1:
        doc_id = doc_ids[most_related_idx]
        return GLOBAL_DOCS[doc_id], DOC_METADATA[doc_id]

    return None, None

def chatbot_rag(message):
    print(f"🤖 Query: {message}")
    context_text, metadata = retrieve_documents_rag(message)
    source_info = "General Knowledge"

    if context_text:
        print(f"✅ Found Context: {metadata['title']}")
        source_info = f"{metadata['title']}"
        prompt = f"""
        You are an agricultural expert. Use the context below to answer.
        Context: "{context_text}"
        Source: {source_info}
        Question: {message}
        Instructions: 1. Base answer on context. 2. Cite source. 3. Answer in Hebrew.
        """
    else:
        print("⚠️ No context found.")
        prompt = f"""
        You are an agricultural expert.
        Question: {message}
        Answer in Hebrew based on general knowledge.
        Start with: "לא מצאתי מאמר ספציפי, אך מהידע הכללי..."
        """

    try:
        response = model.generate_content(prompt)
        return response.text.replace("\n", "<br>")
    except Exception as e:
        return f"Error: {str(e)}"

# --- Part 3: Visualization ---
def generate_sensor_graph_for_display():
    try:
        data = FBconn.get('/sensor_data', None)
        if data and isinstance(data, dict):
             df = pd.DataFrame.from_dict(data, orient='index')
        else:
             return "No Data Found"

        if 'timestamp' in df.columns:
            df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')
            df = df.dropna(subset=['timestamp']).sort_values('timestamp')

        plt.figure(figsize=(10, 5))
        if 'temperature' in df.columns:
            plt.plot(df['timestamp'], df['temperature'], marker='o', linestyle='-', color='green', label='Temperature (°C)')
        if 'humidity' in df.columns:
            plt.plot(df['timestamp'], df['humidity'], marker='x', linestyle='--', color='blue', label='Humidity (%)')
        if 'soil' in df.columns:
            plt.plot(df['timestamp'], df['soil'], marker='s', linestyle=':', color='brown', label='Soil Moisture')

        plt.title('GardenSense: Multi-Sensor Trends')
        plt.xlabel('Date/Time')
        plt.ylabel('Values')
        plt.legend()
        plt.grid(True, alpha=0.3)
        plt.tight_layout()

        buf = io.BytesIO()
        plt.savefig(buf, format='png')
        buf.seek(0)
        img_str = base64.b64encode(buf.read()).decode('utf-8')
        plt.close()
        return f"data:image/png;base64,{img_str}"
    except Exception as e:
        return f"Graph Error: {e}"

output.register_callback('chatbot_rag', chatbot_rag)
output.register_callback('generate_sensor_graph_for_display', generate_sensor_graph_for_display)

print("✅ Backend Ready (With URLs).")

# @title Cell 5: Frontend Application (UI)
from IPython.display import display, HTML
import json

html_content = '''<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>GardenSense</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:'Segoe UI',sans-serif;background:linear-gradient(135deg,#e8f5e8 0%,#f0f8f0 100%);min-height:100vh}
.header{background:linear-gradient(135deg,#2d5a2d 0%,#4a7c59 100%);color:white;padding:1rem 2rem;display:flex;justify-content:space-between;align-items:center;box-shadow:0 2px 10px rgba(0,0,0,0.1)}
.logo{font-size:1.8rem;font-weight:bold}
.nav{display:flex;gap:1rem}
.nav button{background:none;border:none;color:white;padding:0.5rem 1rem;border-radius:20px;cursor:pointer;transition:all 0.3s;font-size:0.9rem}
.nav button.active,.nav button:hover{background:rgba(255,255,255,0.2)}
.container{max-width:1400px;margin:0 auto;padding:1rem}
.page{display:none}
.page.active{display:block}
.page-header{text-align:center;margin-bottom:2rem}
.page-header h1{color:#2d5a2d;font-size:3rem;margin-bottom:0.5rem}
.page-header p{color:#666;font-size:1.5rem}
.section{background:white;border-radius:20px;padding:2rem;box-shadow:0 8px 30px rgba(0,0,0,0.1);margin-bottom:2rem;font-size:1.2rem;line-height:1.6}
.stats-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:1rem;margin-bottom:2rem}
.stat-card{background:white;border-radius:15px;padding:1.5rem;box-shadow:0 4px 20px rgba(0,0,0,0.1);text-align:center}
.stat-icon{font-size:2.5rem;margin-bottom:1rem}
.stat-value{font-size:2.5rem;font-weight:bold;color:#2d5a2d}
.stat-label{color:#666;margin-top:0.5rem;font-size:1.1rem}
.plant-selector{background:white;border:3px solid #e0e0e0;border-radius:15px;padding:1.5rem;cursor:pointer;transition:all 0.3s;text-align:center}
.plant-selector:hover{border-color:#4a7c59;transform:translateY(-2px)}
.plant-selector.active{border-color:#4a7c59;background:#e8f5e8}
.btn{background:linear-gradient(135deg,#4a7c59 0%,#2d5a2d 100%);color:white;border:none;padding:0.8rem 1.5rem;border-radius:20px;cursor:pointer;transition:all 0.3s;font-size:1rem;margin-right:0.5rem}
.btn:hover{transform:translateY(-2px);box-shadow:0 8px 25px rgba(45,90,45,0.3)}
.sensors-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:1.5rem;margin-bottom:2rem}
.sensor-card{background:white;border-radius:20px;padding:1.5rem;box-shadow:0 8px 30px rgba(0,0,0,0.1)}
.sensor-header{display:flex;justify-content:space-between;align-items:center;margin-bottom:1rem}
.sensor-title{display:flex;align-items:center;gap:0.5rem;color:#2d5a2d;font-size:1.6rem;font-weight:bold}
.sensor-status{padding:0.4rem 1rem;border-radius:20px;font-size:1rem;font-weight:bold}
.status-online{background:#e8f5e8;color:#2d5a2d}
.status-warning{background:#fff8e1;color:#ff9800}
.sensor-value{font-size:3.5rem;font-weight:bold;color:#4a7c59;text-align:center;margin:1rem 0}
.sensor-unit{font-size:1.5rem;color:#666}
.search-container{display:flex;gap:1rem;max-width:800px;margin:0 auto 2rem}
.search-input{flex:1;padding:1rem 1.5rem;border:3px solid #e0e0e0;border-radius:25px;font-size:1.3rem; direction:rtl; text-align:right;}
.search-btn{padding:1rem 2rem;border:none;border-radius:25px;background:linear-gradient(135deg,#4a7c59 0%,#2d5a2d 100%);color:white;cursor:pointer;font-size:1.1rem}
.results-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(350px,1fr));gap:1.5rem}
.result-card{background:white;border-radius:15px;padding:1.5rem;box-shadow:0 8px 30px rgba(0,0,0,0.1);border-left:4px solid #4a7c59}
.result-title{color:#2d5a2d;font-size:1.5rem;font-weight:bold;margin-bottom:0.5rem}
.result-description{color:#666;line-height:1.5;font-size:1.1rem}
.chat-container{background:white;border-radius:20px;padding:2rem;box-shadow:0 8px 30px rgba(0,0,0,0.1);max-width:900px;margin:0 auto}
.chat-messages{height:500px;overflow-y:auto;border:2px solid #e0e0e0;border-radius:15px;padding:1.5rem;margin-bottom:1rem;background:#f8fbf8; direction: rtl;}
.message{margin-bottom:1rem;padding:1rem;border-radius:10px;max-width:80%; direction: rtl; text-align: right; unicode-bidi: embed;}
.message.user{background:linear-gradient(135deg,#4a7c59 0%,#2d5a2d 100%);color:white;margin-right:auto; margin-left: 0;}
.message.bot{background:#e8f5e8;color:#2d5a2d;}
.alert-card{background:white;border-radius:15px;padding:1.5rem;margin-bottom:1rem;box-shadow:0 8px 30px rgba(0,0,0,0.1);border-left:6px solid #f44336;animation:slideIn 0.5s}
.alert-card.warning{border-left-color:#ff9800}
.alert-card.info{border-left-color:#2196f3}
.alert-header{display:flex;justify-content:space-between;align-items:center;margin-bottom:1rem}
.alert-title{font-size:1.4rem;font-weight:bold;color:#2d5a2d}
.alert-time{font-size:1rem;color:#666}
.alert-message{font-size:1.2rem;line-height:1.5;margin-bottom:1rem}
.alert-actions{display:flex;gap:1rem}
.alert-btn{padding:0.5rem 1rem;border:none;border-radius:10px;cursor:pointer;font-size:1rem;transition:all 0.3s}
.btn-resolve{background:#4a7c59;color:white}
.btn-snooze{background:#ff9800;color:white}
.btn-dismiss{background:#666;color:white}
.sound-toggle{position:fixed;bottom:20px;right:20px;background:#4a7c59;color:white;border:none;border-radius:50%;width:60px;height:60px;font-size:1.5rem;cursor:pointer;box-shadow:0 4px 20px rgba(0,0,0,0.2);transition:all 0.3s;z-index:1000;display:none}
.sound-toggle:hover{transform:scale(1.1)}
.sound-toggle.muted{background:#666}
@keyframes pulse{0%{opacity:1;transform:scale(1)}50%{opacity:0.5;transform:scale(1.1)}100%{opacity:1;transform:scale(1)}}@keyframes slideIn{from{transform:translateX(100%);opacity:0}to{transform:translateX(0);opacity:1}}
</style></head><body>
<header class="header">
<div class="logo">🌱 GardenSense</div>
<nav class="nav">
<button onclick="showPage('chatbot')" class="active" id="nav-chatbot">🤖 AI Chatbot</button>
<button onclick="showPage('dashboard')" id="nav-dashboard">Dashboard</button>
<button onclick="showPage('upload')" id="nav-upload">Upload</button>
<button onclick="showPage('sensors')" id="nav-sensors">Sensors</button>
<button onclick="showPage('search')" id="nav-search">Search</button>
<button onclick="showPage('analytics')" id="nav-analytics">Analytics</button>
<button onclick="showPage('alerts')" id="nav-alerts">Smart Alerts</button>
</nav>
</header>
<div class="container">
<div id="chatbot" class="page active">
<div class="page-header"><h1>🤖 AI Smart Assistant</h1><p>Powered by Gemini + RAG from Firebase</p></div>
<div class="chat-container">
<div class="chat-messages" id="chatMessages">
<div class="message bot">👋 שלום! אני העוזר החכם של GardenSense. שאל אותי כל שאלה!</div>
</div>
<div style="display:flex;gap:1rem">
<input type="text" class="search-input" id="chatInput" placeholder="שאל שאלה..." onkeypress="if(event.key==='Enter')sendMessage()">
<button class="search-btn" onclick="sendMessage()">📤 שלח</button>
</div></div></div>

<div id="dashboard" class="page">
<div class="page-header"><h1>🏠 Plant Dashboard</h1><p>Select a plant to view detailed information</p></div>
<div class="section">
<h2 style="font-size:1.8rem;margin-bottom:1rem">🌿 Select Plant</h2>
<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:1rem;margin-bottom:2rem">
<button class="plant-selector active" onclick="selectPlant('monstera')" id="plant-monstera">
<div style="font-size:2rem;margin-bottom:0.5rem">🌿</div>
<div style="font-size:1.2rem;font-weight:bold">Monstera Deliciosa</div>
</button>
<button class="plant-selector" onclick="selectPlant('snake')" id="plant-snake">
<div style="font-size:2rem;margin-bottom:0.5rem">🌵</div>
<div style="font-size:1.2rem;font-weight:bold">Snake Plant</div>
</button>
<button class="plant-selector" onclick="selectPlant('peace')" id="plant-peace">
<div style="font-size:2rem;margin-bottom:0.5rem">🌺</div>
<div style="font-size:1.2rem;font-weight:bold">Peace Lily</div>
</button>
<button class="plant-selector" onclick="selectPlant('fiddle')" id="plant-fiddle">
<div style="font-size:2rem;margin-bottom:0.5rem">🍃</div>
<div style="font-size:1.2rem;font-weight:bold">Fiddle Leaf Fig</div>
</button>
</div></div>
<div id="plantDetails">
<div class="section">
<h2 style="font-size:2rem;margin-bottom:1rem" id="selectedPlantName">🌿 Monstera Deliciosa</h2>
<div class="stats-grid">
<div class="stat-card"><div class="stat-icon">🌡️</div><div class="stat-value" id="plantTemp">24.5°C</div><div class="stat-label">Temperature</div></div>
<div class="stat-card"><div class="stat-icon">💧</div><div class="stat-value" id="plantHumidity">68%</div><div class="stat-label">Humidity</div></div>
<div class="stat-card"><div class="stat-icon">🌱</div><div class="stat-value" id="plantSoil">32%</div><div class="stat-label">Soil Moisture</div></div>
<div class="stat-card"><div class="stat-icon">☀️</div><div class="stat-value" id="plantLight">650 lux</div><div class="stat-label">Light Level</div></div>
</div></div>
<div class="section">
<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:1rem">
<h2 style="font-size:1.8rem">📊 Plant Status</h2>
<div style="font-size:1.1rem;color:#666;display:flex;align-items:center;gap:0.5rem">
<div style="width:10px;height:10px;background:#4a7c59;border-radius:50%;animation:pulse 2s infinite"></div>Live Data
</div></div>
<div style="display:grid;grid-template-columns:1fr 1fr;gap:2rem">
<div>
<p style="font-size:1.3rem;margin-bottom:0.8rem"><strong>Health:</strong> <span id="plantHealth" style="color:#4a7c59">Healthy</span></p>
<p style="font-size:1.3rem;margin-bottom:0.8rem"><strong>Last Watered:</strong> <span id="lastWatered">2 days ago</span></p>
<p style="font-size:1.3rem;margin-bottom:0.8rem"><strong>Next Watering:</strong> <span id="nextWatering">In 1 day</span></p>
<p style="font-size:1.3rem"><strong>Growth Stage:</strong> <span id="growthStage">Mature</span></p>
</div>
<div>
<p style="font-size:1.3rem;margin-bottom:0.8rem"><strong>Location:</strong> <span id="plantLocation">Living Room</span></p>
<p style="font-size:1.3rem;margin-bottom:0.8rem"><strong>Age:</strong> <span id="plantAge">2 years</span></p>
<p style="font-size:1.3rem;margin-bottom:0.8rem"><strong>Fertilized:</strong> <span id="lastFertilized">1 week ago</span></p>
<p style="font-size:1.3rem"><strong>Sensor ID:</strong> <span id="sensorId">SENS_001</span></p>
</div></div></div>
<div class="section">
<h2 style="font-size:1.8rem;margin-bottom:1rem">🎯 Care Recommendations</h2>
<div id="careRecommendations">
<p style="font-size:1.3rem;margin-bottom:0.8rem">⚠️ <strong>Urgent:</strong> Soil moisture low</p>
<p style="font-size:1.3rem;margin-bottom:0.8rem">💡 <strong>Tip:</strong> Move to brighter location</p>
<p style="font-size:1.3rem">📅 <strong>Schedule:</strong> Next fertilizing in 3 weeks</p>
</div></div></div></div>
<div id="upload" class="page">
<div class="page-header"><h1>📸 Upload Images</h1><p>Upload plant images</p></div>
<div class="section">
<div style="border:3px dashed #4a7c59;border-radius:15px;padding:3rem;text-align:center;background:#f8fbf8" id="uploadArea">
<div style="font-size:4rem;margin-bottom:1rem;color:#4a7c59">📷</div>
<div style="font-size:1.8rem;color:#2d5a2d;margin-bottom:0.5rem">Drag images here or click to upload</div>
<div style="color:#666;margin-bottom:2rem;font-size:1.2rem">Supports JPG, PNG up to 10MB</div>
<button class="btn" onclick="document.getElementById('fileInput').click()">Select Images</button>
<input type="file" id="fileInput" style="display:none" multiple accept="image/*">
</div>
<div id="uploadStatus" style="margin-top:1rem;padding:1rem;border-radius:10px;display:none"></div>
</div>
<div class="section" id="uploadResults" style="display:none">
<h2>Analysis Results</h2>
<img id="previewImage" style="width:100%;max-width:300px;height:200px;object-fit:cover;border-radius:10px;margin:1rem auto;display:none">
<div id="analysisResults"></div>
</div></div>

<div id="sensors" class="page">
<div class="page-header"><h1>📡 IoT Sensors</h1><p>משיכת נתונים משרת בראודה ושמירה ב-Firebase</p></div>
<div class="section">
    <div style="display:flex; flex-direction:column; gap:1rem; max-width:400px; margin:0 auto;">
        <label for="feedSelect" style="font-size:1.2rem; font-weight:bold;">בחר Feed:</label>
        <select id="feedSelect" style="padding:0.8rem; border-radius:10px; border:1px solid #ccc; font-size:1.1rem;">
            <option value="json" selected>JSON (כל החיישנים)</option>
            <option value="temperature">Temperature</option>
            <option value="humidity">Humidity</option>
            <option value="soil">Soil</option>
        </select>

        <label for="limitSlider" style="font-size:1.2rem; font-weight:bold; margin-top:1rem;">כמות דגימות (1-50):</label>
        <input type="range" id="limitSlider" min="1" max="50" value="10" oninput="document.getElementById('limitValue').innerText=this.value">
        <span id="limitValue" style="font-size:1.1rem; text-align:center;">10</span>

        <button class="btn" style="margin-top:1.5rem;" onclick="fetchAndSave()">🚀 משוך ושמור ל-Firebase</button>
    </div>
    <div id="fetchOutput" style="margin-top:2rem; padding:1rem; background:#f8fbf8; border-radius:10px; border:1px solid #e0e0e0; min-height:100px; overflow-y:auto; font-size:1rem; line-height:1.4;"></div>
</div>

<div class="section">
    <h2 style="font-size:1.8rem;margin-bottom:1rem">📊 Sensor Data Trends</h2>
    <button class="btn" onclick="generateAndDisplayGraph()">📈 הצג גרף נתונים</button>
    <div id="graphContainer" style="margin-top:1.5rem; text-align:center;">
        <img id="sensorGraphImage" style="max-width:100%; height:auto; border-radius:10px; box-shadow:0 4px 20px rgba(0,0,0,0.1); display:none;" alt="Sensor Data Graph">
        <p id="graphStatus" style="color:#666; margin-top:1rem;"></p>
    </div>
</div>

</div>

<div id="search" class="page">
<div class="page-header"><h1>🔍 Search</h1><p>Search garden database</p></div>
<div class="search-container">
<input type="text" class="search-input" id="localSearchInput" placeholder="Type keyword...">
<button class="search-btn" onclick="performLocalSearch()">🔍 Search</button>
</div>
<div class="results-grid" id="localSearchResults">
<div class="result-card">
<div class="result-title">🌿 Quick Search</div>
<div class="result-description">Enter keyword to search database</div>
</div></div></div>

<div id="analytics" class="page">
<div class="page-header"><h1>📊 Analytics</h1><p>Garden insights</p></div>
<div class="stats-grid">
<div class="stat-card"><div class="stat-icon">🌱</div><div class="stat-value">24</div><div class="stat-label">Total Plants</div></div>
<div class="stat-card"><div class="stat-icon">💚</div><div class="stat-value">21</div><div class="stat-label">Healthy</div></div>
<div class="stat-card"><div class="stat-icon">⚠️</div><div class="stat-value">3</div><div class="stat-label">Alerts</div></div>
<div class="stat-card"><div class="stat-icon">📊</div><div class="stat-value">8.7</div><div class="stat-label">Health Score</div></div>
</div>
<div class="section">
<h2 style="font-size:1.8rem;margin-bottom:1rem">🎯 Smart Insights</h2>
<p style="font-size:1.3rem;margin-bottom:1rem">💡 <strong>Care:</strong> 3 plants need watering today</p>
<p style="font-size:1.3rem;margin-bottom:1rem">⚡ <strong>Energy:</strong> Natural light high</p>
<p style="font-size:1.3rem">🔔 <strong>Alert:</strong> Monstera needs water soon</p>
</div></div>

<div id="alerts" class="page">
<div class="page-header"><h1>🚨 Smart Alerts</h1><p>Real-time notifications</p></div>
<div class="section">
<div style="display:flex;justify-content:space-between;margin-bottom:2rem">
<h2 style="font-size:1.8rem">🔔 Active Alerts</h2>
<div>
<button class="btn" onclick="testAlert()">🧪 Test</button>
<button class="btn" onclick="clearAllAlerts()">🗑️ Clear</button>
</div></div>
<div id="alertsList">
<div class="alert-card">
<div class="alert-header">
<div class="alert-title">🚨 Critical: Low Soil Moisture</div>
<div class="alert-time">2 min ago</div>
</div>
<div class="alert-message">Monstera soil moisture dropped to 15%. Immediate watering required.</div>
<div class="alert-actions">
<button class="alert-btn btn-resolve" onclick="resolveAlert(this)">✅ Resolve</button>
<button class="alert-btn btn-snooze" onclick="snoozeAlert(this)">⏰ Snooze</button>
<button class="alert-btn btn-dismiss" onclick="dismissAlert(this)">❌ Dismiss</button>
</div></div>
<div class="alert-card warning">
<div class="alert-header">
<div class="alert-title">⚠️ Warning: High Temperature</div>
<div class="alert-time">15 min ago</div>
</div>
<div class="alert-message">Temperature reached 32°C. Consider ventilation.</div>
<div class="alert-actions">
<button class="alert-btn btn-resolve" onclick="resolveAlert(this)">✅ Resolve</button>
<button class="alert-btn btn-snooze" onclick="snoozeAlert(this)">⏰ Snooze</button>
<button class="alert-btn btn-dismiss" onclick="dismissAlert(this)">❌ Dismiss</button>
</div></div>
<div class="alert-card info">
<div class="alert-header">
<div class="alert-title">ℹ️ Info: Fertilizing Reminder</div>
<div class="alert-time">1 hour ago</div>
</div>
<div class="alert-message">Peace Lily due for fertilizing.</div>
<div class="alert-actions">
<button class="alert-btn btn-resolve" onclick="resolveAlert(this)">✅ Resolve</button>
<button class="alert-btn btn-snooze" onclick="snoozeAlert(this)">⏰ Snooze</button>
<button class="alert-btn btn-dismiss" onclick="dismissAlert(this)">❌ Dismiss</button>
</div></div>
</div></div>
<div class="section">
<h2 style="font-size:1.8rem;margin-bottom:1rem">⚙️ Alert Settings</h2>
<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:2rem">
<div>
<h3 style="margin-bottom:1rem">🔊 Sound Notifications</h3>
<label style="display:flex;align-items:center;gap:1rem;margin-bottom:1rem">
<input type="checkbox" id="soundEnabled" checked style="transform:scale(1.5)">
<span style="font-size:1.2rem">Enable sound alerts</span>
</label>
<label style="display:flex;align-items:center;gap:1rem">
<span style="font-size:1.2rem">Volume:</span>
<input type="range" id="volumeSlider" min="0" max="100" value="70" style="flex:1" oninput="updateVolumeDisplay()">
<span id="volumeDisplay" style="font-size:1.2rem">70%</span>
</label>
</div>
<div>
<h3 style="margin-bottom:1rem">📱 Alert Types</h3>
<label style="display:flex;align-items:center;gap:1rem;margin-bottom:0.5rem">
<input type="checkbox" checked style="transform:scale(1.5)">
<span style="font-size:1.2rem">Critical alerts (immediate action)</span>
</label>
<label style="display:flex;align-items:center;gap:1rem;margin-bottom:0.5rem">
<input type="checkbox" checked style="transform:scale(1.5)">
<span style="font-size:1.2rem">Warning alerts (attention needed)</span>
</label>
<label style="display:flex;align-items:center;gap:1rem">
<input type="checkbox" checked style="transform:scale(1.5)">
<span style="font-size:1.2rem">Info alerts (reminders)</span>
</label>
</div>
</div>
</div>
</div>
<button class="sound-toggle" id="soundToggle" onclick="toggleSound()" title="Toggle Sound">🔊</button>
<script>
let samplingInterval,isRunning=false,dashboardInterval,soundEnabled=true,alertVolume=0.7;
const plantData={monstera:{name:'🌿 Monstera Deliciosa',temp:'24.5°C',humidity:'68%',soil:'32%',light:'650 lux',health:'Needs Water',healthColor:'#ff9800',lastWatered:'2 days ago',nextWatering:'Today',location:'Living Room',age:'2 years',growthStage:'Mature',lastFertilized:'1 week ago',sensorId:'SENS_001',recommendations:['⚠️ <strong>Urgent:</strong> Soil moisture low','💡 <strong>Tip:</strong> Move to brighter location','📅 <strong>Schedule:</strong> Fertilizing in 3 weeks']},snake:{name:'🌵 Snake Plant',temp:'22.1°C',humidity:'45%',soil:'55%',light:'320 lux',health:'Excellent',healthColor:'#4a7c59',lastWatered:'1 week ago',nextWatering:'In 1 week',location:'Bedroom',age:'3 years',growthStage:'Mature',lastFertilized:'2 months ago',sensorId:'SENS_002',recommendations:['✅ <strong>Perfect:</strong> All optimal','💡 <strong>Tip:</strong> Low maintenance','📅 <strong>Schedule:</strong> Fertilizing in 2 months']},peace:{name:'🌺 Peace Lily',temp:'23.8°C',humidity:'72%',soil:'78%',light:'520 lux',health:'Blooming',healthColor:'#4a7c59',lastWatered:'1 day ago',nextWatering:'In 2 days',location:'Kitchen',age:'1.5 years',growthStage:'Flowering',lastFertilized:'3 days ago',sensorId:'SENS_003',recommendations:['🌸 <strong>Blooming:</strong> Beautiful flowers!','💡 <strong>Tip:</strong> Maintain humidity','📅 <strong>Schedule:</strong> Fertilizing in 2 weeks']},fiddle:{name:'🍃 Fiddle Leaf Fig',temp:'26.2°C',humidity:'58%',soil:'45%',light:'780 lux',health:'Good',healthColor:'#4a7c59',lastWatered:'3 days ago',nextWatering:'In 4 days',location:'Living Room',age:'4 years',growthStage:'Large',lastFertilized:'5 days ago',sensorId:'SENS_004',recommendations:['✅ <strong>Healthy:</strong> Growing well','💡 <strong>Tip:</strong> Rotate weekly','📅 <strong>Schedule:</strong> Fertilizing in 3 weeks']}};
const staticData = [{title:"Monstera Deliciosa Care",content:"Monstera prefers bright indirect light. Water when top 2-3 inches dry. High humidity preferred.",tags:["monstera","care","watering"]},{title:"Snake Plant Guide",content:"Snake Plants are resilient, low light tolerant. Drought-tolerant, allow soil to dry completely.",tags:["snake plant","care","low light"]},{title:"Peace Lily Maintenance",content:"Peace Lilies prefer partial shade. Keep moist but not soggy. Droop when thirsty.",tags:["peace lily","care","watering"]},{title:"Fiddle Leaf Fig Tips",content:"Fiddle Leaf Figs need bright filtered light. Sensitive to drafts. Water when top inch dry.",tags:["fiddle leaf fig","care","light"]}];
const scrapedData = __SEARCH_DATA_PLACEHOLDER__;
const knowledgeBase = [...staticData, ...scrapedData];
function showPage(p){document.querySelectorAll('.page').forEach(e=>e.classList.remove('active'));document.querySelectorAll('.nav button').forEach(e=>e.classList.remove('active'));document.getElementById(p).classList.add('active');document.getElementById('nav-'+p).classList.add('active');const soundBtn=document.getElementById('soundToggle');if(p==='alerts'){soundBtn.style.display='block'}else{soundBtn.style.display='none'}if(p==='dashboard'){selectPlant('monstera');startDashboardUpdates()}else{stopDashboardUpdates()}}
function selectPlant(id){document.querySelectorAll('.plant-selector').forEach(e=>e.classList.remove('active'));document.getElementById('plant-'+id).classList.add('active');const p=plantData[id];document.getElementById('selectedPlantName').textContent=p.name;document.getElementById('plantTemp').textContent=p.temp;document.getElementById('plantHumidity').textContent=p.humidity;document.getElementById('plantSoil').textContent=p.soil;document.getElementById('plantLight').textContent=p.light;document.getElementById('plantHealth').textContent=p.health;document.getElementById('plantHealth').style.color=p.healthColor;document.getElementById('lastWatered').textContent=p.lastWatered;document.getElementById('nextWatering').textContent=p.nextWatering;document.getElementById('plantLocation').textContent=p.location;document.getElementById('plantAge').textContent=p.age;document.getElementById('growthStage').textContent=p.growthStage;document.getElementById('lastFertilized').textContent=p.lastFertilized;document.getElementById('sensorId').textContent=p.sensorId;document.getElementById('careRecommendations').innerHTML=p.recommendations.map(r=>`<p style="font-size:1.3rem;margin-bottom:0.8rem">${r}</p>`).join('')}
function startDashboardUpdates(){if(dashboardInterval)clearInterval(dashboardInterval);dashboardInterval=setInterval(()=>{const a=document.querySelector('.plant-selector.active');if(!a)return;const id=a.id.replace('plant-','');document.getElementById('plantTemp').textContent=(Math.random()*4+22).toFixed(1)+'°C';document.getElementById('plantHumidity').textContent=Math.floor(Math.random()*20+55)+'%';document.getElementById('plantSoil').textContent=Math.floor(Math.random()*30+30)+'%';document.getElementById('lightValue').textContent=Math.floor(Math.random()*200+500)+' lux'},5000)}
function stopDashboardUpdates(){if(dashboardInterval){clearInterval(dashboardInterval);dashboardInterval=null}}
async function sendMessage(){const i=document.getElementById('chatInput'),m=i.value.trim();if(!m)return;const d=document.getElementById('chatMessages');d.innerHTML+=`<div class="message user">${m}</div>`;i.value='';d.scrollTop=d.scrollHeight;d.innerHTML+=`<div class="message bot" id="loading">🤖 חושב...</div>`;d.scrollTop=d.scrollHeight;try{const r=await google.colab.kernel.invokeFunction('chatbot_rag',[m],{});const res=r.data['application/json']||r.data['text/plain']||'שגיאה בקבלת תשובה';document.getElementById('loading').remove();d.innerHTML+=`<div class="message bot">${res}</div>`}catch(e){document.getElementById('loading').remove();d.innerHTML+=`<div class="message bot">❌ שגיאה: ${e.message}</div>`}d.scrollTop=d.scrollHeight}
function startSampling(){if(isRunning)return;isRunning=true;samplingInterval=setInterval(()=>{document.getElementById('tempValue').innerHTML=(Math.random()*10+20).toFixed(1)+'<span class="sensor-unit">°C</span>';document.getElementById('humidityValue').innerHTML=Math.floor(Math.random()*20+60)+'<span class="sensor-unit">%</span>';document.getElementById('soilValue').innerHTML=Math.floor(Math.random()*15+30)+'<span class="sensor-unit">%</span>';document.getElementById('lightValue').innerHTML=Math.floor(Math.random()*200+500)+'<span class="sensor-unit">lux</span>';document.getElementById('lastUpdate').textContent=new Date().toLocaleTimeString()},3000)}
function stopSampling(){if(!isRunning)return;clearInterval(samplingInterval);isRunning=false}
async function exportData(){
    alert("הפקת דוחות (word) הוסרה לבקשת המשתמש.");
}
// New function for fetching and saving data
async function fetchAndSave() {
    const feedSelect = document.getElementById('feedSelect');
    const limitSlider = document.getElementById('limitSlider');
    const fetchOutput = document.getElementById('fetchOutput');

    const selectedFeed = feedSelect.value;
    const selectedLimit = parseInt(limitSlider.value, 10);

    fetchOutput.innerHTML = `📡 מתחבר לשרת ומושך ${selectedLimit} דגימות מסוג '${selectedFeed}'...<br>`;

    try {
        const result = await google.colab.kernel.invokeFunction(
            'fetch_and_save_data_from_braude',
            [selectedFeed, selectedLimit],
            {}
        );
        const message = result.data['application/json'] || result.data['text/plain'] || 'שגיאה: לא התקבלה תשובה מהשרת.';
        fetchOutput.innerHTML += message;
    } catch (e) {
        fetchOutput.innerHTML += `❌ שגיאה בביצוע הפעולה: ${e.message}`;
    }
}

function performLocalSearch(){
    const q = document.getElementById('localSearchInput').value.toLowerCase();
    const r = document.getElementById('localSearchResults');
    if(!q) return;

    const d = knowledgeBase.filter(doc =>
        doc.title.toLowerCase().includes(q) ||
        doc.content.toLowerCase().includes(q) ||
        doc.tags.some(t => q.includes(t))
    );

    if(d.length === 0){
        r.innerHTML = '<div class="result-card"><div class="result-title">No results</div><div class="result-description">Try different keyword</div></div>';
        return;
    }

    let h = '<div class="result-card"><div class="result-title">Found ' + d.length + ' results</div></div>';
    d.forEach(doc => {
        // Link logic: If doc has a URL, make title a link.
        let titleHtml = doc.title;
        if(doc.url) {
            titleHtml = `<a href="${doc.url}" target="_blank" style="text-decoration:none; color:#2d5a2d; display:flex; justify-content:space-between; align-items:center;">
                            ${doc.title} <span style="font-size:0.8em;">🔗</span>
                         </a>`;
        }

        h += `<div class="result-card">
                <div class="result-title">${titleHtml}</div>
                <div class="result-description">${doc.content}</div>
              </div>`;
    });
    r.innerHTML = h;
}

function playAlertSound(t='critical'){if(!soundEnabled)return;const c=new(window.AudioContext||window.webkitAudioContext)(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);const f={critical:[800,600,800,600],warning:[500,400],info:[300]}[t]||[800,600];let i=0;function p(){if(i>=f.length){o.stop();return}o.frequency.setValueAtTime(f[i],c.currentTime);g.gain.setValueAtTime(alertVolume*0.3,c.currentTime);g.gain.exponentialRampToValueAtTime(0.01,c.currentTime+0.3);i++;setTimeout(p,400)}o.start();p()}
function testAlert(){playAlertSound('critical');alert('🧪 Test Alert with Sound!')}
function resolveAlert(b){b.closest('.alert-card').remove()}
function snoozeAlert(b){const c=b.closest('.alert-card');c.style.opacity='0.5';setTimeout(()=>c.style.opacity='1',5000)}
function dismissAlert(b){b.closest('.alert-card').remove()}
function clearAllAlerts(){document.querySelectorAll('.alert-card').forEach(a=>a.remove())}
function toggleSound(){soundEnabled=!soundEnabled;const b=document.getElementById('soundToggle');b.textContent=soundEnabled?'🔊':'🔇';b.classList.toggle('muted',!soundEnabled);const c=document.getElementById('soundEnabled');if(c)c.checked=soundEnabled}
function generateRandomAlert(){const a=[{title:'💧 Watering Needed',message:'Snake Plant soil low',type:'warning'},{title:'🌡️ Temperature Alert',message:'Temperature rising',type:'warning'},{title:'🌱 Growth Milestone',message:'Monstera grew 2cm!',type:'info'},{title:'🔋 Battery Low',message:'Sensor battery 15%',type:'critical'}];if(Math.random()>0.7){const r=a[Math.floor(Math.random()*a.length)];playAlertSound(r.type)}}
function updateVolumeDisplay(){const v=document.getElementById('volumeSlider'),d=document.getElementById('volumeDisplay');if(v&&d){d.textContent=v.value+'%';alertVolume=v.value/100}}
document.addEventListener('DOMContentLoaded',function(){const v=document.getElementById('volumeSlider'),d=document.getElementById('volumeDisplay'),s=document.getElementById('soundEnabled');if(v){v.addEventListener('input',updateVolumeDisplay);v.addEventListener('change',updateVolumeDisplay)}if(s){s.addEventListener('change',function(){soundEnabled=this.checked;const btn=document.getElementById('soundToggle');if(btn)btn.textContent=soundEnabled?'🔊':'🔇'})}const uploadArea=document.getElementById('uploadArea'),fileInput=document.getElementById('fileInput');if(uploadArea){uploadArea.addEventListener('dragover',e=>{e.preventDefault();uploadArea.style.background='#e8f5e8'});uploadArea.addEventListener('dragleave',()=>{uploadArea.style.background='#f8fbf8'});uploadArea.addEventListener('drop',e=>{e.preventDefault();uploadArea.style.background='#f8fbf8';handleFiles(e.dataTransfer.files)})}if(fileInput){fileInput.addEventListener('change',e=>{handleFiles(e.target.files)})}});
function handleFiles(files){if(files.length>0){const file=files[0];if(file.type.startsWith('image/')){const reader=new FileReader();reader.onload=e=>{const preview=document.getElementById('previewImage');preview.src=e.target.result;preview.style.display='block';document.getElementById('uploadResults').style.display='block';showStatus('מעלה תמונה...','success');setTimeout(()=>{const plants=[{id:'rubber',name:'Rubber Plant',icon:'🌳',confidence:92,health:'Healthy & Thriving',care:'Water twice a week, allow soil to dry between waterings',light:'Bright indirect light, avoid direct sunlight',temp:'65-80°F (18-27°C)',humidity:'50-60% for optimal growth'},{id:'pothos',name:'Golden Pothos',icon:'🌿',confidence:88,health:'Excellent condition',care:'Water when top inch of soil is dry',light:'Low to bright indirect light',temp:'60-85°F (15-29°C)',humidity:'40-60%'},{id:'spider',name:'Spider Plant',icon:'🌱',confidence:95,health:'Very healthy',care:'Water regularly, keep soil moist',light:'Bright indirect light',temp:'55-80°F (13-27°C)',humidity:'40-70%'}];const p=plants[Math.floor(Math.random()*plants.length)];document.getElementById('analysisResults').innerHTML=`<h2 style="font-size:2rem;color:#2d5a2d;margin-bottom:1rem">${p.icon} ${p.name}</h2><p style="font-size:1.3rem;margin-bottom:0.8rem"><strong>Confidence Level:</strong> ${p.confidence}% Match</p><p style="font-size:1.3rem;margin-bottom:0.8rem"><strong>Health Status:</strong> ${p.health}</p><p style="font-size:1.3rem;margin-bottom:0.8rem"><strong>Care Instructions:</strong> ${p.care}</p><p style="font-size:1.3rem;margin-bottom:0.8rem"><strong>Light Requirements:</strong> ${p.light}</p><p style="font-size:1.3rem;margin-bottom:0.8rem"><strong>Temperature:</strong> ${p.temp}</p><p style="font-size:1.3rem;margin-bottom:1rem"><strong>Humidity:</strong> ${p.humidity}</p><button class="btn" style="font-size:1.2rem;padding:1rem 2rem">➕ Add ${p.name} to Dashboard</button>`;showStatus('ניתוח הושלם בהצלחה!','success')},2000)};
reader.readAsDataURL(file)}else{showStatus('בחר קובץ תמונה תקין (JPG/PNG)','error')}}}
function showStatus(msg,type){const s=document.getElementById('uploadStatus');s.textContent=msg;s.style.display='block';s.style.background=type==='success'?'#e8f5e8':'#ffebee';s.style.color=type==='success'?'#2d5a2d':'#f44336';s.style.borderLeft=type==='success'?'4px solid #4a7c59':'4px solid #f44336';setTimeout(()=>s.style.display='none',3000)}

// --- PATCHED GRAPH DISPLAY FUNCTION ---
async function generateAndDisplayGraph() {
    const graphImage = document.getElementById('sensorGraphImage');
    const graphStatus = document.getElementById('graphStatus');

    graphImage.style.display = 'none'; // Hide previous
    graphImage.src = '';
    graphStatus.innerHTML = 'Creating graph... Please wait.';

    try {
        const result = await google.colab.kernel.invokeFunction(
            'generate_sensor_graph_for_display',
            [],
            {}
        );
        let rawImageData = result.data['text/plain'];

        if (typeof rawImageData === 'string') {
            if ((rawImageData.startsWith("'") && rawImageData.endsWith("'")) ||
                (rawImageData.startsWith('"') && rawImageData.endsWith('"'))) {
                rawImageData = rawImageData.slice(1, -1);
            }

            const trimmedImageData = rawImageData.trim();
            const startsWithExpected = trimmedImageData.startsWith('data:image/png;base64,');

            if (startsWithExpected) {
                graphImage.src = trimmedImageData;
                graphImage.style.display = 'block';
                graphStatus.innerHTML = '';
            } else {
                graphStatus.innerHTML = `DEBUG INFO: Image data invalid.`;
            }
        } else {
            graphStatus.innerHTML = `❌ Error: Received unexpected data type.`;
        }
    } catch (e) {
        console.error("JavaScript error during graph generation:", e);
        graphStatus.innerHTML = `❌ Error generating graph: ${e.message}`;
    }
}

setTimeout(()=>{document.getElementById('soundToggle').style.display='none';startDashboardUpdates();setInterval(generateRandomAlert,30000)},1000);
</script></body></html>'''

try:
    search_json = json.dumps(FRONTEND_SEARCH_DATA)
except NameError:
    search_json = "[]"

display(HTML(html_content.replace("__SEARCH_DATA_PLACEHOLDER__", search_json)))